### ISSUE TITLE
Very high idle CPU usage

### ISSUE THREAD

**Issue by DoctorMcKay** [jazz-soft/jazz-midi#1]
I am running a lighting control system off a Raspberry Pi, which has never been an issue before. I've added a MIDI controller to my system using this module, and I've run into an issue where the CPU idles very high with this module. I've confirmed that jazz-midi is the culprit as using [node-midi](https://www.npmjs.com/package/midi) with the exact same code doesn't exhibit the same behavior.

I'm using the latest version 1.7.3, and I've encountered this on both Raspbian and Ubuntu 18.04.4 LTS (on a Core 2 Duo machine).

**Comment by jazz-soft** [comment]
I have published the source code in this repository. If you have any suggestions how to improve it, please let me know!
