### ISSUE TITLE
Test WebMIDI fails

### ISSUE THREAD

**Issue by raphaelbastide** [jazz-soft/jazz-midi#4]
I have installed both the Firefox extension and the jazz-midi node packag. When I browse [this page](https://jazz-soft.net/download/Jazz-Plugin/) I can see the midi icon on the Firefox URL bar and I can playing with the keyboard logo makes sound.

However the test page https://webmidi.info/ reports `✘ Your browser does not support WebMIDI.` and most of the MIDI-compatible web app I test don’t work, because they assume the browse doesn’t support webMIDI. 

Did I miss something?

Tested with OS: linux (debian + XFCE), and Firefox 89

**Comment by jazz-soft** [comment]
To support Web MIDI API, you can install another extension: https://github.com/jazz-soft/web-midi
Hope that will help...

**Comment by raphaelbastide** [comment]
Thank you! I missed that one. Does it mean I need to install two addons and the jazz-midi node package?

**Comment by jazz-soft** [comment]
Yes, that is correct, but you already have most of these installed.

**Comment by raphaelbastide** [comment]
Thank you!
